/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

==> 4613732
*/

package main

import "fmt"

const limit = 4e6

func main() {
	a, b, c, evenSum := 1, 1, 2, 0
	for c < limit {
		if checkEven(c) {
			evenSum += c
		}
		a = b
		b = c
		c = a + b
	}

	fmt.Print("Sum: ", evenSum)
}

func checkEven(i int) bool {
	return i%2 == 0
}
